title: LearnAI: Enterprise Knowledge Mining Bootcamp 

description: Microsoft labs for learning to develop AI-oriented applications.

show_downloads: true

theme: jekyll-theme-cayman

repository: Azure/LearnAI-KnowledgeMiningBootcamp
