theme: jekyll-theme-cayman
title: LearnAI - Enterprise Knowledge Mining Bootcamp
description: Build an enterprise scale intelligent search solution for searching business documents using Microsoft Azure and Cognitive Search.
show_downloads: true
repository: Azure/LearnAI-KnowledgeMiningBootcamp
